/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.rnziparchive;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReactModuleWithSpec;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeZipArchiveSpec extends ReactContextBaseJavaModule implements ReactModuleWithSpec, TurboModule {
  public static final String NAME = "RNZipArchive";

  public NativeZipArchiveSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void isPasswordProtected(String file, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void unzip(String from, String destinationPath, String charset, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void unzipWithPassword(String from, String destinationPath, String password, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void zipFolder(String from, String destinationPath, double compressionLevel, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void zipFiles(ReadableArray from, String destinationPath, double compressionLevel, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void zipFolderWithPassword(String from, String destinationPath, String password, String encryptionType, double compressionLevel, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void zipFilesWithPassword(ReadableArray from, String destinationPath, String password, String encryptionType, double compressionLevel, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getUncompressedSize(String path, String charset, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void unzipAssets(String source, String target, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void addListener(String eventName);

  @ReactMethod
  @DoNotStrip
  public abstract void removeListeners(double count);
}
